apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bloodconnect

type: Opaque
data:
  POSTGRES_DB: Ymxvb2RfZGI=
  POSTGRES_USER: Ymxvb2RfdXNlcg==
  POSTGRES_PASSWORD: Ymxvb2RfcGFzcw==
