# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"\x1b\n\x0bTestRequest\x12\x0c\n\x04ping\x18\x01 \x01(\t\"\x1e\n\x0cTestResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2E\n\x11PredictionService\x12\x30\n\x0bHealthCheck\x12\x0f.ai.TestRequest\x1a\x10.ai.TestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTREQUEST']._serialized_start=16
  _globals['_TESTREQUEST']._serialized_end=43
  _globals['_TESTRESPONSE']._serialized_start=45
  _globals['_TESTRESPONSE']._serialized_end=75
  _globals['_PREDICTIONSERVICE']._serialized_start=77
  _globals['_PREDICTIONSERVICE']._serialized_end=146
# @@protoc_insertion_point(module_scope)
