# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forecasting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'forecasting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66orecasting.proto\x12\x0b\x66orecasting\"/\n\x0f\x46orecastRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\"W\n\x11\x42loodTypeForecast\x12\x12\n\nblood_type\x18\x01 \x01(\t\x12\x1a\n\x12predicted_quantity\x18\x02 \x01(\x01\x12\x12\n\nconfidence\x18\x03 \x01(\x01\"r\n\x10\x46orecastResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\r\n\x05month\x18\x03 \x01(\t\x12\x31\n\tforecasts\x18\x04 \x03(\x0b\x32\x1e.forecasting.BloodTypeForecast2e\n\x12\x46orecastingService\x12O\n\x10PredictNextMonth\x12\x1c.forecasting.ForecastRequest\x1a\x1d.forecasting.ForecastResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forecasting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORECASTREQUEST']._serialized_start=34
  _globals['_FORECASTREQUEST']._serialized_end=81
  _globals['_BLOODTYPEFORECAST']._serialized_start=83
  _globals['_BLOODTYPEFORECAST']._serialized_end=170
  _globals['_FORECASTRESPONSE']._serialized_start=172
  _globals['_FORECASTRESPONSE']._serialized_end=286
  _globals['_FORECASTINGSERVICE']._serialized_start=288
  _globals['_FORECASTINGSERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
